version: '3'

services:
  api:
    build:
      context: api      
    ports:
      - 127.0.0.1:5003:80
    volumes:
      - ./api:/opt/api

  frontend:
    build:
      context: frontend
    ports:
      - 127.0.0.1:5004:3000
    volumes:
      - ./frontend:/app/src