version: '3.8'

services:
  api:
    build:
      context: api      
    ports:
      - 127.0.0.1:5003:80
    volumes:
    - ./api:/opt/api
    - ./hackathon.db:/opt/hackathon.db
    environment:
      - DB_PATH=/opt/hackathon.db
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  frontend:
    build:
      context: frontend
    ports:
      - 127.0.0.1:5004:3000
