version: '3.8'

services:
  api:
    build:
      context: api      
    ports:
      - 127.0.0.1:5003:80
    volumes:
    - ./api:/opt/api
    - ./hackaton.db:/opt/api/hackaton.db
    environment:
      - DB_PATH=/opt/api/hackaton.db
    #   - NVIDIA_VISIBLE_DEVICES=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]

  frontend:
    build:
      context: frontend
    ports:
      - 127.0.0.1:5004:3000
    volumes:
      - ./frontend:/app/src
      - /app/src/node_modules
